name: Expo CI/CD

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run lint
              run: npx expo lint

            - name: Install EAS CLI
              run: npm install -g eas-cli

            - name: Login to Expo
              if: github.event_name == 'push'
              run: npx eas-cli login --token ${{ secrets.TERRAFY }}

            - name: Build Android
              if: github.event_name == 'push'
              run: npx eas-cli build --platform android --non-interactive
