name: Expo CI/CD

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run lint
              run: npx expo lint

            - name: Install EAS CLI
              run: npm install -g eas-cli@latest

            - name: Login to Expo
              run: npx eas-cli whoami
              env:
                  EXPO_TOKEN: ${{ secrets.TERRAFY }}

            - name: Build Android
              run: npx eas-cli@latest build --platform android --non-interactive
              env:
                  EXPO_TOKEN: ${{ secrets.TERRAFY }}
